#!/usr/bin/env bash
# Two arguments expected:
#    1: Name of the slice
#    2: Network UUID to be assigned to the controller of the slice

unset ERR
if [[ -n "$1" ]]; then
    SLICE_NAME=$1
else
    echo "Must specify first parameter (Name of the slice)"
    ERR=1
fi
if [[ -n "$2" ]]; then
    NET_UUID=$2
else
    echo "Must specify second parameter (Network UUID)"
    ERR=1
fi

if [[ -z "$ERR" ]]; then
    TOKEN=`keystone token-get | grep ' id ' | awk -F '|' '{print $3}'`

    curl -H "X-Auth-Token:$TOKEN" http://$RYU_API_HOST:$RYU_API_PORT/v1/network/flowvisor/$SLICE_NAME/assign/$NET_UUID -X PUT
fi
