#!/usr/bin/env bash
# Three arguments expected:
#    1: Name of the slice
#    2: IP address of the slice controller
#    3: Port number of the slice controller

unset ERR
if [[ -n "$1" ]]; then
    SLICE_NAME=$1
else
    echo "Must specify first parameter (Name of the slice)"
    ERR=1
fi
if [[ -n "$2" ]]; then
    CTRL_IP_ADDR=$2
else
    echo "Must specify second parameter (Controller's IP address)"
    ERR=1
fi
if [[ -n "$3" ]]; then
    CTRL_PORT_NUM=$3
else
    echo "Must specify third parameter (Controller's port number)"
    ERR=1
fi

if [[ -z "$ERR" ]]; then
    TOKEN=`keystone token-get | grep ' id ' | awk -F '|' '{print $3}'`

    curl -H "X-Auth-Token:$TOKEN" http://$RYU_API_HOST:$RYU_API_PORT/v1/network/flowvisor/"$SLICE_NAME"_"$CTRL_IP_ADDR"_"$CTRL_PORT_NUM" -X POST
fi
