#!/usr/bin/env bash
# Command line: source ryu_fvctl_rc {RYU API HOST IP} {RYU API PORT NUMBER}

unset ERR
if [[ -n "$1" ]]; then
    RYU_API_HOST=$1
else
    echo "Must specify first parameter (Ryu API host IP)"
    ERR=1
fi
if [[ -n "$2" ]]; then
    RYU_API_PORT=$2
else
    echo "Must specify second parameter (Ryu API port number)"
    ERR=1
fi

if [[ -z "$ERR" ]]; then
    export RYU_API_HOST
    export RYU_API_PORT
fi
