#!/usr/bin/env bash
# One argument expected:
#    1: Network UUID to be assigned to the controller of the slice

unset ERR
if [[ -n "$1" ]]; then
    NET_UUID=$1
else
    echo "Must specify second parameter (Network UUID)"
    ERR=1
fi

if [[ -z "$ERR" ]]; then
    TOKEN=`keystone token-get | grep ' id ' | awk -F '|' '{print $3}'`

    curl -H "X-Auth-Token:$TOKEN" http://$RYU_API_HOST:$RYU_API_PORT/v1/network/flowvisor/unassign/$NET_UUID -X PUT
fi
